version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - wget https://github.com/priyatamv/codedeploydemo.git
   post_build:
    commands:
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  files:
     type: zip
      files:
        - 'ROOT/WEB-INF/**/*'
        - 'ROOT/WEB-INF/codedeploydemo/*'
        - 'ROOT/WEB-INF/codedeploydemo/customers/eos/*'
