version: 0.1

phases:
  install:
    commands:
      - echo Entering install phase...
      - wget https://github.com/priyatamv/codedeploydemo.git
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
   post_build:
    commands:
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  files:
     type: zip
      files:
        - 'ROOT/WEB-INF/**/*'
        - 'ROOT/WEB-INF/codedeploydemo/*'
        - 'ROOT/WEB-INF/codedeploydemo/customers/eos/*'
