version: 0.1

phases:
  install:
    commands:
      - echo Entering install phase...
      - wget https://github.com/priyatamv/codedeploydemo.git -C /tmp/
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date` for code build
      - /codebuild/output/src064299797/src/github.com/priyatamv/codedeploydemo/scripts/build-script.sh
   post_build:
    commands:
      - echo Build completed on `date`
