version: 0.1

phases:
  install:
    commands:
      - echo Entering install phase...
      - wget https://github.com/priyatamv/codedeploydemo.git
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
     - /codedeploydemo/scripts/build-script.sh
